// apps/frontend/src/modules/features/pipeline/presentation/ui/dashboard/pipeline-table/PipelineStatus.tsx
import StatusIndicator, {
  type StatusState,
} from '@shared/presentation/ui/data-display/status-indicator.tsx';
import { Trans } from '@lingui/react/macro';
import type { PipelineMetadata } from '@/modules/features/pipeline/domain/structs/pipeline.struct.ts';

type PipelineStatusProps = {
  pipeline: PipelineMetadata;
  status: StatusState;
};

/**
 * Component to display the status of a pipeline, including its name, branch, commit hash, and creation date.
 */
export const PipelineStatus = ({ pipeline, status }: PipelineStatusProps) => {
  const creationDate = new Date(pipeline.createdAt);

  return (
    <div className={'flex items-center justify-center gap-2 flex-row'}>
      <StatusIndicator state={status} />

      <div className='flex flex-col overflow-hidden'>
        <span className='font-semibold text-slate-900 truncate'>{pipeline.name}</span>
        <span className='text-xs text-slate-500'>
          <Trans>Creation:</Trans> {creationDate.toDateString()}
        </span>
        <span className={'text-xs text-slate-400'}>id: {pipeline.id}</span>
      </div>
    </div>
  );
};

// apps/frontend/src/modules/features/pipeline/presentation/ui/dashboard/pipeline-table/PipelineStatus.svelte
<script lang="ts">
  import {
    CopyableText,
    StatusIndicator,
    type StatusState,
  } from '@shared/presentation/ui-svelte';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import { formatDay } from '@shared/utils/date-utils.ts';
  import type { PipelineMetadata } from '../../../../domain/structs/pipeline.struct.ts';
  import { pipelineMessages } from '../../../pipeline.messages.ts';

  interface Props {
    pipeline: PipelineMetadata;
    status: StatusState;
  }

  let { pipeline, status }: Props = $props();
</script>

<!-- A pipeline's identity cell: how its last run went, then its name, creation
     day and (copyable) id. -->
<div class="flex w-full flex-row items-center justify-start gap-2">
  <!-- The pill is not the line that should give way when the column narrows. -->
  <div class="shrink-0">
    <StatusIndicator state={status} />
  </div>

  <!-- Stretched, not `items-start`: on the cross axis a flex-start child is sized to
       its own text, so `truncate`'s nowrap made every line as wide as its content and
       there was nothing left to ellipsize — it just overflowed into the clipped cell. -->
  <div class="flex min-w-0 flex-1 flex-col text-start">
    <span class="truncate font-semibold text-foreground">{pipeline.name}</span>
    <span class="truncate text-xs text-muted-foreground">
      {t(pipelineMessages.creation)}
      {formatDay(pipeline.createdAt)}
    </span>
    <CopyableText class="text-xs text-muted-foreground/80" value={pipeline.id} />
  </div>
</div>
