// apps/frontend/src/modules/features/triggers/presentation/ui/triggers-table/TriggersTable.tsx
import { useState } from 'react';
import { DataTable } from '@shared/presentation/ui/data-display/DataTable.tsx';
import { ConfirmOperationAlertDialog } from '@shared/presentation/ui/feedback/ConfirmOperationAlertDialog.tsx';
import { useFeatureSelection } from '@shared/presentation/hooks/use-feature-selection.ts';
import { Permission, useCan } from '@platform/authz';
import { Trans, useLingui } from '@lingui/react/macro';
import { TriggerKind } from '@/modules/features/triggers/domain/structs/trigger-source.struct.ts';
import { useScyllaNavigate } from '@platform/context';
import type { TriggerEntity } from '@/modules/features/triggers/domain/entities/trigger.entity.ts';
import { useDeleteTrigger } from '@/modules/features/triggers/presentation/hooks/use-delete-trigger.ts';
import { useSetTriggerEnabled } from '@/modules/features/triggers/presentation/hooks/use-set-trigger-enabled.ts';
import { useFireTriggerNow } from '@/modules/features/triggers/presentation/hooks/use-fire-trigger-now.ts';
import { TriggerFormDialog } from '@/modules/features/triggers/presentation/ui/dialogs/TriggerFormDialog.tsx';
import { createTriggerColumns } from './columns.tsx';

interface TriggersTableProps {
  triggers: TriggerEntity[];
  pipelineId: string;
  pipelineName: string;
}

export const TriggersTable = ({ triggers, pipelineId, pipelineName }: TriggersTableProps) => {
  const deleteTrigger = useDeleteTrigger(pipelineId);
  const { selectedIds, select, headerProps } = useFeatureSelection(
    'triggers',
    triggers.map(trigger => trigger.id),
    { deleteItem: id => deleteTrigger.mutateAsync(id) },
  );
  // Triggers are all-or-nothing in V1: one permission covers create and delete.
  const canManage = useCan(Permission.MANAGE_TRIGGERS);
  const { t } = useLingui();
  const { goToJobs } = useScyllaNavigate();
  const setEnabled = useSetTriggerEnabled(pipelineId);
  const fireNow = useFireTriggerNow(pipelineId);

  const [editTarget, setEditTarget] = useState<TriggerEntity | null>(null);
  const [deleteTargetId, setDeleteTargetId] = useState<string | null>(null);
  const [firingIds, setFiringIds] = useState<Set<string>>(new Set());

  const handleFire = (trigger: TriggerEntity) => {
    setFiringIds(prev => new Set(prev).add(trigger.id));
    fireNow
      .mutateAsync(trigger.id)
      // Close the loop: land on the run we just created.
      .then(() => goToJobs(pipelineId, pipelineName))
      .catch(() => {
        // Toast shown by the global MutationCache onError handler.
      })
      .finally(() =>
        setFiringIds(prev => {
          const next = new Set(prev);
          next.delete(trigger.id);
          return next;
        }),
      );
  };

  const columns = createTriggerColumns({
    onFire: handleFire,
    onEdit: trigger => setEditTarget(trigger),
    onDelete: triggerId => setDeleteTargetId(triggerId),
    onToggleEnabled: (trigger, enabled) => setEnabled.mutate({ triggerId: trigger.id, enabled }),
    firingIds,
  });

  return (
    <>
      <DataTable
        columns={columns}
        data={triggers}
        onRowClick={row => select(row.original.id)}
        getRowId={row => row.id}
        isRowSelected={row => selectedIds.includes(row.id)}
        searchable
        searchPlaceholder={t`Search a trigger…`}
        searchValues={trigger => [trigger.name, trigger.id]}
        facets={[
          {
            id: 'source',
            label: t`Source`,
            value: trigger => trigger.source.kind,
            options: [
              { value: TriggerKind.Cron, label: t`Cron` },
              { value: TriggerKind.Webhook, label: t`Webhook` },
            ],
          },
          {
            id: 'enabled',
            label: t`State`,
            value: trigger => (trigger.enabled ? 'enabled' : 'disabled'),
            options: [
              { value: 'enabled', label: t`Enabled` },
              { value: 'disabled', label: t`Disabled` },
            ],
          },
        ]}
        selection={{
          ...headerProps,
          canDelete: canManage,
          deleteDeniedReason: <Trans>You don't have permission to manage triggers.</Trans>,
        }}
        alignColumnsCenter
      />

      {editTarget && (
        <TriggerFormDialog
          open={editTarget !== null}
          onOpenChange={open => {
            if (!open) setEditTarget(null);
          }}
          pipelineId={pipelineId}
          trigger={editTarget}
        />
      )}

      <ConfirmOperationAlertDialog
        open={deleteTargetId !== null}
        onOpenChange={open => {
          if (!open) setDeleteTargetId(null);
        }}
        onContinue={() => {
          if (!deleteTargetId) return;
          deleteTrigger.mutate(deleteTargetId);
          setDeleteTargetId(null);
        }}
      />
    </>
  );
};

// apps/frontend/src/modules/features/triggers/presentation/ui/triggers-table/TriggersTable.svelte
<script lang="ts">
  import ClockIcon from '@lucide/svelte/icons/clock';
  import HelpCircleIcon from '@lucide/svelte/icons/help-circle';
  import WebhookIcon from '@lucide/svelte/icons/webhook';
  import { scyllaNavigate } from '@platform/context';
  import { createMutation } from '@platform/query';
  import { Switch } from '@shadcn-svelte';
  import {
    ConfirmOperationAlertDialog,
    CopyableText,
    DataTable,
  } from '@shared/presentation/ui-svelte';
  import { createSelection } from '@shared/presentation/state/selection.svelte.ts';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import type { TriggerEntity } from '../../../domain/entities/trigger.entity.ts';
  import { TriggerKind } from '../../../domain/structs/trigger-source.struct.ts';
  import { triggerMutations } from '../../triggers.queries.ts';
  import TriggerActions from './TriggerActions.svelte';
  import TriggerSourceCell from './TriggerSourceCell.svelte';
  import TriggerStatusCell from './TriggerStatusCell.svelte';
  import TriggerFormDialog from '../dialogs/TriggerFormDialog.svelte';
  import { triggerColumns } from './trigger-columns.ts';
  import { triggersMessages } from '../triggers.messages.ts';

  interface Props {
    triggers: TriggerEntity[];
    pipelineId: string;
    pipelineName: string;
  }

  let { triggers, pipelineId, pipelineName }: Props = $props();

  const SOURCE_ICON = {
    [TriggerKind.Cron]: ClockIcon,
    [TriggerKind.Webhook]: WebhookIcon,
    [TriggerKind.Unknown]: HelpCircleIcon,
  } as const;

  const selection = createSelection('triggers');
  const deleteTrigger = createMutation(() => triggerMutations.remove(pipelineId));
  const setEnabled = createMutation(() => triggerMutations.setEnabled(pipelineId));
  const fireNow = createMutation(() => triggerMutations.fireNow(pipelineId));

  let editTarget = $state<TriggerEntity | null>(null);
  let deleteTargetId = $state<string | null>(null);
  /** Per-row, because two rows can be firing at once. */
  let firingIds = $state(new Set<string>());

  const handleFire = (trigger: TriggerEntity) => {
    firingIds = new Set(firingIds).add(trigger.id);

    fireNow
      .mutateAsync(trigger.id)
      // Close the loop: land on the run we just created.
      .then(() => scyllaNavigate.goToJobs(pipelineId, pipelineName))
      .catch(() => {
        // Toast shown by the global MutationCache onError handler.
      })
      .finally(() => {
        const next = new Set(firingIds);
        next.delete(trigger.id);
        firingIds = next;
      });
  };

  const columns = $derived(
    triggerColumns({
      name: nameCell,
      source: sourceCell,
      status: statusCell,
      enabled: enabledCell,
      actions: actionsCell,
    }),
  );
</script>

{#snippet nameCell(trigger: TriggerEntity)}
  {@const Icon = SOURCE_ICON[trigger.source.kind]}
  <div class="flex w-full min-w-0 flex-row items-center gap-3">
    <div class="flex size-10 shrink-0 items-center justify-center rounded-lg bg-primary/10">
      <Icon class="size-4 text-primary" />
    </div>
    <div class="flex min-w-0 flex-col text-start">
      <p class="truncate font-semibold text-foreground">{trigger.name}</p>
      <CopyableText
        class="text-xs text-muted-foreground/80"
        value={trigger.id}
        display={`ID: ${trigger.id}`}
      />
    </div>
  </div>
{/snippet}

{#snippet sourceCell(trigger: TriggerEntity)}
  <TriggerSourceCell {trigger} />
{/snippet}

{#snippet statusCell(trigger: TriggerEntity)}
  <TriggerStatusCell {trigger} />
{/snippet}

{#snippet enabledCell(trigger: TriggerEntity)}
  <!-- Stop propagation so toggling the switch doesn't also select the row. -->
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div class="flex justify-center" onclick={event => event.stopPropagation()}>
    <Switch
      checked={trigger.enabled}
      onCheckedChange={checked => setEnabled.mutate({ triggerId: trigger.id, enabled: checked })}
      aria-label={t(triggersMessages.toggleEnabled(trigger.name))}
    />
  </div>
{/snippet}

{#snippet actionsCell(trigger: TriggerEntity)}
  <TriggerActions
    isFiring={firingIds.has(trigger.id)}
    onFire={event => {
      event.stopPropagation();
      handleFire(trigger);
    }}
    onEdit={event => {
      event.stopPropagation();
      editTarget = trigger;
    }}
    onDelete={event => {
      event.stopPropagation();
      deleteTargetId = trigger.id;
    }}
  />
{/snippet}

<DataTable
  {columns}
  data={triggers}
  onRowClick={row => selection.select(row.original.id)}
  getRowId={trigger => trigger.id}
  isRowSelected={trigger => selection.selectedIds.includes(trigger.id)}
  alignColumnsCenter
/>

{#if editTarget}
  <TriggerFormDialog
    open
    onOpenChange={open => {
      if (!open) editTarget = null;
    }}
    {pipelineId}
    trigger={editTarget}
  />
{/if}

<ConfirmOperationAlertDialog
  open={deleteTargetId !== null}
  onOpenChange={open => {
    if (!open) deleteTargetId = null;
  }}
  onContinue={() => {
    if (!deleteTargetId) return;
    deleteTrigger.mutate(deleteTargetId);
    deleteTargetId = null;
  }}
/>
