// apps/frontend/src/modules/features/triggers/presentation/ui/triggers-table/TriggerSourceCell.tsx
import { Clock, Webhook } from 'lucide-react';
import { Badge } from '@shadcn';
import { CodeSnippet } from '@shadcn/code-snippet.tsx';
import { TriggerKind } from '@/modules/features/triggers/domain/models/trigger-source.model.ts';
import type { TriggerEntity } from '@/modules/features/triggers/domain/entities/trigger.entity.ts';
import { convertCronToLocal } from '@/modules/features/triggers/presentation/utils/trigger-form.utils.ts';

/** Cron triggers show their expression; webhook triggers show their (copyable) URL. */
export const TriggerSourceCell = ({ trigger }: { trigger: TriggerEntity }) => {
  if (trigger.source.kind === TriggerKind.Cron) {
    return (
      <div className='flex items-center gap-2'>
        <Badge variant='secondary' className='gap-1'>
          <Clock className='size-3' /> Cron
        </Badge>
        <code className='font-mono text-xs text-muted-foreground'>
          {convertCronToLocal(trigger.source.expression) || '—'}
        </code>
      </div>
    );
  }

  return (
    <div className='flex flex-col items-start gap-1'>
      <Badge variant='secondary' className='gap-1'>
        <Webhook className='size-3' /> Webhook
      </Badge>
      {trigger.source.webhookUrl && (
        <CodeSnippet value={trigger.source.webhookUrl} className='w-full max-w-xs' />
      )}
    </div>
  );
};

// apps/frontend/src/modules/features/triggers/presentation/ui/triggers-table/TriggerSourceCell.svelte
<script lang="ts">
  import { CopyableText } from '@shared/presentation/ui-svelte';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import type { TriggerEntity } from '../../../domain/entities/trigger.entity.ts';
  import { TriggerKind } from '../../../domain/structs/trigger-source.struct.ts';
  import { convertCronToLocal } from '../../utils/trigger-form.utils.ts';
  import { triggersMessages } from '../triggers.messages.ts';

  interface Props {
    trigger: TriggerEntity;
  }

  let { trigger }: Props = $props();
</script>

<!-- Cron triggers show their expression; webhook triggers show their (copyable) URL. -->
{#if trigger.source.kind === TriggerKind.Cron}
  <div class="flex items-center justify-center gap-2">
    <code class="font-mono text-xs text-muted-foreground">
      {convertCronToLocal(trigger.source.expression) || '—'}
    </code>
  </div>
{:else if trigger.source.kind === TriggerKind.Webhook}
  <CopyableText
    value={trigger.source.webhookUrl}
    showFullOnHover
    copyLabel={t(triggersMessages.copyUrl)}
    class="w-full justify-center"
  />
{:else}
  <!-- A source arm this build doesn't know: nothing meaningful to render. -->
  <div class="flex items-center justify-center">
    <code class="font-mono text-xs text-muted-foreground">—</code>
  </div>
{/if}
