// apps/frontend/src/modules/features/jobs/presentation/ui/JobsHeader.tsx
import { Button } from '@shadcn';
import { RefreshCw } from 'lucide-react';
import { useDeleteJobs } from '@/modules/features/jobs/presentation/hooks/use-delete-jobs.ts';
import { Tooltip, TooltipContent, TooltipTrigger } from '@shadcn/tooltip.tsx';
import { Trans } from '@lingui/react/macro';
import { FeatureHeader } from '@shared/presentation/ui';
import { useFeatureSelection } from '@shared/presentation/hooks/use-feature-selection.ts';
import { Permission } from '@platform/authz/domain/structs/permission.struct.ts';
import { useCan } from '@platform/authz/presentation/hooks/use-authorization.ts';

interface JobsHeaderProps {
  numberOfJobs: number;
  jobIds: string[];
  pipelineId: string;
  onRefresh: () => void;
  /**
   * Runs the pipeline these jobs belong to. Injected by whoever owns the route,
   * because running is a pipeline operation — jobs would otherwise have to
   * import the pipeline module that already reads jobs.
   */
  onRun?: () => Promise<void>;
}

export const JobsHeader = ({
  numberOfJobs,
  jobIds,
  pipelineId,
  onRefresh,
  onRun,
}: JobsHeaderProps) => {
  const deleteJob = useDeleteJobs(pipelineId);
  const { headerProps } = useFeatureSelection('jobs', jobIds, {
    deleteItem: id => deleteJob.mutateAsync(id),
  });

  const canRun = useCan(Permission.RUN_PIPELINE);
  const canDelete = useCan(Permission.DELETE_JOB);

  return (
    <div className={'flex flex-col gap-3'}>
      <FeatureHeader
        count={numberOfJobs}
        label={<Trans>Job</Trans>}
        pluralLabel={<Trans>Jobs</Trans>}
        newLabel={<Trans>Run</Trans>}
        onNew={onRun ? () => void onRun() : undefined}
        canNew={canRun}
        newDeniedReason={<Trans>You don't have permission to run this pipeline.</Trans>}
        canDelete={canDelete}
        deleteDeniedReason={<Trans>You don't have permission to delete jobs.</Trans>}
        {...headerProps}
        underLabel={
          <div className={'flex items-center justify-between'}>
            <div className='flex items-baseline gap-2'>
              <span className='text-sm text-muted-foreground font-medium'>
                <Trans>Pipeline ID: {pipelineId}</Trans>
              </span>
            </div>
          </div>
        }
        extraActions={
          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                variant={'outline'}
                size='icon'
                onClick={onRefresh}
                className='h-9 w-9 cursor-pointer transition-all hover:scale-110'
              >
                <RefreshCw className='size-4' />
              </Button>
            </TooltipTrigger>
            <TooltipContent>
              <p>
                <Trans>Refresh</Trans>
              </p>
            </TooltipContent>
          </Tooltip>
        }
      />
    </div>
  );
};

// apps/frontend/src/modules/features/jobs/presentation/ui/JobsHeader.svelte
<script lang="ts">
  import RefreshCwIcon from '@lucide/svelte/icons/refresh-cw';
  import { Permission, can } from '@platform/authz';
  import { createMutation } from '@platform/query';
  import { Button, Tooltip, TooltipContent, TooltipTrigger } from '@shadcn-svelte';
  import { CopyableText, FeatureHeader } from '@shared/presentation/ui-svelte';
  import { createFeatureSelection } from '@shared/presentation/state/feature-selection.svelte.ts';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import { jobMutations } from '../jobs.queries.ts';
  import { jobsMessages } from './jobs.messages.ts';

  interface Props {
    numberOfJobs: number;
    jobIds: string[];
    pipelineId: string;
    onRefresh: () => void;
    /**
     * Runs the pipeline these jobs belong to. Injected by whoever owns the
     * route, because running is a pipeline operation — jobs would otherwise
     * have to import the pipeline module that already reads jobs.
     */
    onRun?: () => Promise<void>;
  }

  let { numberOfJobs, jobIds, pipelineId, onRefresh, onRun }: Props = $props();

  const deleteJob = createMutation(() => jobMutations.remove(pipelineId));

  // A getter, not the array: the ids are server data that arrives late, and
  // capturing them once would freeze "select all" on the first, empty render.
  const selection = createFeatureSelection('jobs', () => jobIds, {
    deleteItem: id => deleteJob.mutateAsync(id),
  });

  const canRun = $derived(can(Permission.RUN_PIPELINE));
  const canDelete = $derived(can(Permission.DELETE_JOB));
</script>

{#snippet pipelineIdLine()}
  <div class="flex items-center justify-between">
    <div class="flex items-center gap-2">
      <span class="text-sm text-muted-foreground font-medium">
        {t(jobsMessages.pipelineIdLabel)}
      </span>
      <CopyableText value={pipelineId} class="text-sm text-muted-foreground font-medium" />
    </div>
  </div>
{/snippet}

{#snippet refreshAction()}
  <Tooltip>
    <TooltipTrigger>
      {#snippet child({ props })}
        <Button
          {...props}
          variant="outline"
          size="icon"
          onclick={onRefresh}
          class="h-9 w-9 cursor-pointer transition-all hover:scale-110"
        >
          <RefreshCwIcon class="size-4" />
          <!-- The tooltip is only `aria-describedby`: without this the button
               has no accessible name while it is closed. -->
          <span class="sr-only">{t(jobsMessages.refresh)}</span>
        </Button>
      {/snippet}
    </TooltipTrigger>
    <TooltipContent>
      <p>{t(jobsMessages.refresh)}</p>
    </TooltipContent>
  </Tooltip>
{/snippet}

<div class="flex flex-col gap-3">
  <FeatureHeader
    count={numberOfJobs}
    label={t(jobsMessages.job)}
    pluralLabel={t(jobsMessages.jobs)}
    newLabel={t(jobsMessages.run)}
    onNew={onRun ? () => void onRun() : undefined}
    canNew={canRun}
    newDeniedReason={t(jobsMessages.runDenied)}
    {canDelete}
    deleteDeniedReason={t(jobsMessages.deleteDenied)}
    underLabel={pipelineIdLine}
    extraActions={refreshAction}
    {...selection.headerProps}
  />
</div>
