// apps/frontend/src/modules/features/roles/presentation/ui/components/role-detail/RoleDetailGrantList.svelte
<script lang="ts">
  import AppWindowIcon from '@lucide/svelte/icons/app-window';
  import Building2Icon from '@lucide/svelte/icons/building-2';
  import FolderGit2Icon from '@lucide/svelte/icons/folder-git-2';
  import GlobeIcon from '@lucide/svelte/icons/globe';
  import UserIcon from '@lucide/svelte/icons/user';
  import XIcon from '@lucide/svelte/icons/x';
  import { can, Permission, PermissionScope, PrincipalKind } from '@platform/authz';
  import { Badge } from '@shadcn-svelte';
  import { IconButton } from '@shared/presentation/ui-svelte';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import type { RoleEntity } from '../../../../domain/entities/role.entity.ts';
  import { createGrantTargetLabels } from '../../../grant-target-labels.svelte.ts';
  import { createRoleAssignees } from '../../../role-assignees.state.svelte.ts';
  import { rolesMessages } from '../../roles.messages.ts';
  import GrantCreator from './GrantCreator.svelte';

  interface Props {
    role: RoleEntity;
  }

  let { role }: Props = $props();

  const assignees = createRoleAssignees(() => role);
  const targets = createGrantTargetLabels(() => role.scope);

  const SCOPE_ICON = {
    [PermissionScope.SYSTEM]: GlobeIcon,
    [PermissionScope.ORGANIZATION]: Building2Icon,
    [PermissionScope.PROJECT]: FolderGit2Icon,
    [PermissionScope.UNSPECIFIED]: GlobeIcon,
  };

  // Revoking is the mirror of granting: system-wide, administrators only.
  const canRevoke = $derived(can(Permission.MANAGE_SYSTEM_GRANTS));
</script>

<section class="flex min-h-0 flex-col gap-2">
  <div class="flex items-center justify-between">
    <h3 class="text-xs font-semibold tracking-wider text-muted-foreground uppercase">
      {t(rolesMessages.grants)} ({assignees.assignees.length})
    </h3>

    <GrantCreator {role} />
  </div>

  {#if assignees.assignees.length === 0}
    <p class="rounded-lg border border-dashed py-6 text-center text-sm text-muted-foreground">
      {t(rolesMessages.noGrants)}
    </p>
  {:else}
    <!--
      A plain overflow container rather than the shared `ScrollArea`: that
      component's root is only `relative`, so a `max-h-*` on it clips nothing and
      a long grant list spills over whatever follows.
    -->
    <div class="max-h-72 overflow-y-auto">
      <ul class="flex flex-col gap-2 pr-2">
        {#each assignees.assignees as { grant, label } (grant.id)}
          {@const isUser = grant.principal.kind === PrincipalKind.USER}
          {@const target = targets.labelFor(grant.scopeId)}
          {@const ScopeIcon = SCOPE_ICON[role.scope] ?? GlobeIcon}
          <li class="flex items-center gap-3 rounded-lg border px-3 py-2">
            <div class="flex size-9 shrink-0 items-center justify-center rounded-lg bg-primary/10">
              {#if isUser}
                <UserIcon class="size-4 text-primary" />
              {:else}
                <AppWindowIcon class="size-4 text-primary" />
              {/if}
            </div>
            <div class="flex min-w-0 flex-col items-start gap-1">
              <p class="max-w-full truncate font-medium text-foreground">{label}</p>
              <Badge variant="secondary" class="max-w-full gap-1 font-normal">
                <ScopeIcon class="size-3 shrink-0" />
                <span class="truncate">
                  {target.organizationName ? `${target.organizationName} / ` : ''}{target.name}
                </span>
              </Badge>
            </div>
            <IconButton
              icon={XIcon}
              tooltip={canRevoke ? t(rolesMessages.remove) : t(rolesMessages.revokeDenied)}
              disabled={!canRevoke}
              class="ml-auto hover:text-destructive"
              onclick={() => assignees.remove(grant.id)}
            />
          </li>
        {/each}
      </ul>
    </div>
  {/if}
</section>

// apps/frontend/src/modules/features/roles/presentation/ui/components/role-detail/RoleDetailGrantList.tsx
import { Trans } from '@lingui/react/macro';
import { Badge } from '@shadcn';
import { ScrollArea } from '@shadcn/scroll-area.tsx';
import { AppWindow, Building2, FolderGit2, Globe, User, X } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { IconButton } from '@shared/presentation/ui';
import {
  Permission,
  PermissionScope,
  PrincipalKind,
} from '@platform/authz/domain/structs/permission.struct.ts';
import { useCan } from '@platform/authz/presentation/hooks/use-authorization.ts';
import type { RoleEntity } from '@/modules/features/roles/domain/entities/role.entity.ts';
import { useRoleAssignees } from '@/modules/features/roles/presentation/hooks/use-role-assignees.ts';
import {
  useGrantTargetLabels,
  type GrantTargetLabel,
} from '@/modules/features/roles/presentation/hooks/use-grant-target-labels.ts';
import GrantCreator from '@/modules/features/roles/presentation/ui/components/role-detail/GrantCreator.tsx';

interface RoleDetailGrantsProps {
  role: RoleEntity;
}

const scopeIcon: Record<PermissionScope, LucideIcon> = {
  [PermissionScope.SYSTEM]: Globe,
  [PermissionScope.ORGANIZATION]: Building2,
  [PermissionScope.PROJECT]: FolderGit2,
  [PermissionScope.UNSPECIFIED]: Globe,
};

/** The scope target of a grant, resolved to a name, shown as an icon chip. */
const ScopeTargetBadge = ({
  scope,
  target,
}: {
  scope: PermissionScope;
  target: GrantTargetLabel;
}) => {
  const Icon = scopeIcon[scope] ?? Globe;
  return (
    <Badge variant='secondary' className='gap-1 font-normal max-w-full'>
      <Icon className='size-3 shrink-0' />
      <span className='truncate'>
        {target.organizationName ? `${target.organizationName} / ` : ''}
        {target.name}
      </span>
    </Badge>
  );
};

export const RoleDetailGrantList = ({ role }: RoleDetailGrantsProps) => {
  const { assignees, removeAssignee } = useRoleAssignees(role);
  const { labelFor } = useGrantTargetLabels(role.scope);
  // Revoking is the mirror of granting: system-wide, administrators only.
  const canRevoke = useCan(Permission.MANAGE_SYSTEM_GRANTS);

  return (
    <section className='flex flex-col gap-2 min-h-0'>
      <div className='flex items-center justify-between'>
        <h3 className='text-xs font-semibold uppercase tracking-wider text-slate-500'>
          <Trans>Grants</Trans> ({assignees.length})
        </h3>

        <GrantCreator role={role} />
      </div>
      {assignees.length === 0 ? (
        <p className='rounded-lg border border-dashed py-6 text-center text-sm text-muted-foreground'>
          <Trans>No one holds this role yet.</Trans>
        </p>
      ) : (
        <ScrollArea className='max-h-72'>
          <ul className='flex flex-col gap-2 pr-2'>
            {assignees.map(({ grant, label }) => {
              const isUser = grant.principal.kind === PrincipalKind.USER;
              const target = labelFor(grant.scopeId);
              return (
                <li
                  key={grant.id}
                  className='flex items-center gap-3 rounded-lg border border px-3 py-2'
                >
                  <div className='flex size-9 items-center justify-center rounded-lg bg-primary/10 shrink-0'>
                    {isUser ? (
                      <User className='size-4 text-primary' />
                    ) : (
                      <AppWindow className='size-4 text-primary' />
                    )}
                  </div>
                  <div className='flex flex-col items-start gap-1 min-w-0'>
                    <p className='font-medium text-foreground truncate max-w-full'>{label}</p>
                    <ScopeTargetBadge scope={role.scope} target={target} />
                  </div>
                  <IconButton
                    icon={X}
                    tooltip={
                      canRevoke ? (
                        <Trans>Remove</Trans>
                      ) : (
                        <Trans>You don't have permission to revoke grants.</Trans>
                      )
                    }
                    disabled={!canRevoke}
                    className='ml-auto hover:text-destructive'
                    onClick={() => removeAssignee(grant.id)}
                  />
                </li>
              );
            })}
          </ul>
        </ScrollArea>
      )}
    </section>
  );
};

export default RoleDetailGrantList;
