// apps/frontend/src/modules/features/triggers/presentation/ui/components/TriggersHeader.tsx
import { Trans } from '@lingui/react/macro';
import { FeatureHeader } from '@shared/presentation/ui';
import { useFeatureSelection } from '@shared/presentation/hooks/use-feature-selection.ts';
import { useDeleteTrigger } from '@/modules/features/triggers/presentation/hooks/use-delete-trigger.ts';
import { Permission } from '@platform/authz/domain/structs/permission.struct.ts';
import { useCan } from '@platform/authz/presentation/hooks/use-authorization.ts';

interface TriggersHeaderProps {
  count: number;
  triggerIds: string[];
  pipelineId: string;
  onNew: () => void;
  isNew?: boolean;
}

export const TriggersHeader = ({
  count,
  triggerIds,
  pipelineId,
  onNew,
  isNew,
}: TriggersHeaderProps) => {
  const deleteTrigger = useDeleteTrigger(pipelineId);
  const { headerProps } = useFeatureSelection('triggers', triggerIds, {
    deleteItem: id => deleteTrigger.mutateAsync(id),
  });

  // Triggers are all-or-nothing in V1: one permission covers create and delete.
  const canManage = useCan(Permission.MANAGE_TRIGGERS);

  return (
    <FeatureHeader
      count={count}
      label={<Trans>Trigger</Trans>}
      pluralLabel={<Trans>Triggers</Trans>}
      newLabel={<Trans>New trigger</Trans>}
      onNew={onNew}
      isNew={isNew}
      canNew={canManage}
      newDeniedReason={<Trans>You don't have permission to manage triggers.</Trans>}
      canDelete={canManage}
      deleteDeniedReason={<Trans>You don't have permission to manage triggers.</Trans>}
      {...headerProps}
      underLabel={
        <span className='text-sm text-muted-foreground font-medium'>
          <Trans>Pipeline ID: {pipelineId}</Trans>
        </span>
      }
    />
  );
};

// apps/frontend/src/modules/features/triggers/presentation/ui/components/TriggersHeader.svelte
<script lang="ts">
  import { can, Permission } from '@platform/authz';
  import { createMutation } from '@platform/query';
  import { CopyableText, FeatureHeader } from '@shared/presentation/ui-svelte';
  import { createFeatureSelection } from '@shared/presentation/state/feature-selection.svelte.ts';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import { triggerMutations } from '../../triggers.queries.ts';
  import { triggersMessages } from '../triggers.messages.ts';

  interface Props {
    count: number;
    triggerIds: string[];
    pipelineId: string;
    onNew: () => void;
  }

  let { count, triggerIds, pipelineId, onNew }: Props = $props();

  const deleteTrigger = createMutation(() => triggerMutations.remove(pipelineId));

  // A getter, not the array: the ids are server data that arrives late, and
  // capturing them once would freeze "select all" on the first, empty render.
  const selection = createFeatureSelection('triggers', () => triggerIds, {
    deleteItem: id => deleteTrigger.mutateAsync(id),
  });

  // Triggers are all-or-nothing in V1: one permission covers create and delete.
  const canManage = $derived(can(Permission.MANAGE_TRIGGERS));
</script>

{#snippet pipelineIdLine()}
  <div class="flex items-center gap-2">
    <span class="text-sm text-muted-foreground font-medium">
      {t(triggersMessages.pipelineIdLabel)}
    </span>
    <CopyableText value={pipelineId} class="text-sm text-muted-foreground font-medium" />
  </div>
{/snippet}

<FeatureHeader
  {count}
  label={t(triggersMessages.trigger)}
  pluralLabel={t(triggersMessages.triggers)}
  newLabel={t(triggersMessages.newTrigger)}
  {onNew}
  canNew={canManage}
  newDeniedReason={t(triggersMessages.manageDenied)}
  canDelete={canManage}
  deleteDeniedReason={t(triggersMessages.manageDenied)}
  underLabel={pipelineIdLine}
  {...selection.headerProps}
/>
