// apps/frontend/src/modules/features/roles/presentation/ui/Roles.page.svelte
<script lang="ts">
  import { FeatureHeader } from '@shared/presentation/ui';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import { createRolesPage } from '../roles-page.state.svelte.ts';
  import RoleDetailPanel from './components/RoleDetailPanel.svelte';
  import RoleListItem from './components/RoleListItem.svelte';
  import RoleFormDialog from './components/role-form/RoleFormDialog.svelte';
  import { rolesMessages } from './roles.messages.ts';

  const page = createRolesPage();
</script>

<!--
  Access-control administration: the role catalog on the left, one role's
  permissions and grants on the right.

  Holding `MANAGE_ROLES` is what opens this page *and* what carries grant
  management with it, so the whole screen is behind one gate — but the two
  destructive controls still ask for themselves, because the route guard is not
  the thing the backend enforces.
-->
<div class="flex h-full min-h-0 w-full flex-col gap-4">
  <FeatureHeader
    count={page.roles.length}
    label={t(rolesMessages.role)}
    pluralLabel={t(rolesMessages.roles)}
    newLabel={t(rolesMessages.createRole)}
    onNew={page.canManageRoles ? page.openCreate : undefined}
    {...page.selection.headerProps}
  />

  <div
    class="grid min-h-0 flex-1 grid-cols-1 gap-4 lg:grid-cols-[minmax(0,1.1fr)_minmax(0,1fr)]"
  >
    <div class="flex min-h-0 flex-col gap-2 overflow-y-auto pr-1">
      {#if page.roles.length === 0}
        <p
          class="rounded-xl border border-dashed border-slate-200 py-10 text-center text-sm text-muted-foreground"
        >
          {t(rolesMessages.noRoles)}
        </p>
      {:else}
        {#each page.roles as role (role.id)}
          <RoleListItem
            {role}
            memberCount={page.memberCountOf(role.id)}
            active={role.id === page.activeRoleId}
            selected={page.selection.isSelected(role.id)}
            selectable={page.isSelectable(role)}
            onOpen={() => page.open(role.id)}
            onToggleSelect={() => page.selection.select(role.id)}
          />
        {/each}
      {/if}
    </div>

    <div class="min-h-0 rounded-xl border bg-background p-5 shadow-sm">
      <RoleDetailPanel role={page.activeRole} onEdit={page.openEdit} />
    </div>
  </div>

  <RoleFormDialog open={page.formOpen} role={page.editingRole} onClose={page.closeForm} />
</div>

// apps/frontend/src/modules/features/role/presentation/ui/Roles.page.tsx
import { useMemo, useState } from 'react';
import { useFeatureSelection } from '@shared/presentation/hooks/use-feature-selection.ts';
import { Trans } from '@lingui/react/macro';
import type { RoleEntity } from '@/modules/features/role/domain/entities/role.entity.ts';
import { useRoles } from '@/modules/features/role/presentation/hooks/use-roles.ts';
import { useGrants } from '@/modules/features/role/presentation/hooks/use-grants.ts';
import { RolesHeader } from '@/modules/features/role/presentation/ui/RolesHeader.tsx';
import { RoleListItem } from '@/modules/features/role/presentation/ui/components/RoleListItem.tsx';
import { RoleDetailPanel } from '@/modules/features/role/presentation/ui/components/RoleDetailPanel.tsx';
import { RoleFormDialog } from '@/modules/features/role/presentation/ui/components/RoleFormDialog.tsx';

export const RolesPage = () => {
  const { roles, deleteRole } = useRoles();
  const { grants } = useGrants();

  const [activeRoleId, setActiveRoleId] = useState<string | null>(null);
  const [formOpen, setFormOpen] = useState(false);
  const [editingRole, setEditingRole] = useState<RoleEntity | null>(null);

  const { isSelected, select, headerProps } = useFeatureSelection(
    'roles',
    useMemo(() => roles.map(role => role.id), [roles]),
    { deleteItem: (id: string) => deleteRole.mutateAsync(id) },
  );

  // Members per role, derived from the grant list (no extra request).
  const memberCounts = useMemo(() => {
    const counts = new Map<string, number>();
    for (const grant of grants) {
      if (grant.target.kind === 'role') {
        counts.set(grant.target.roleId, (counts.get(grant.target.roleId) ?? 0) + 1);
      }
    }
    return counts;
  }, [grants]);

  const activeRole = roles.find(role => role.id === activeRoleId) ?? null;

  const openCreate = () => {
    setEditingRole(null);
    setFormOpen(true);
  };

  const openEdit = (role: RoleEntity) => {
    setEditingRole(role);
    setFormOpen(true);
  };

  return (
    <div className='flex flex-col gap-4 w-full h-full min-h-0'>
      <RolesHeader count={roles.length} onNew={openCreate} {...headerProps} />

      <div className='grid flex-1 min-h-0 grid-cols-1 gap-4 lg:grid-cols-[minmax(0,1.1fr)_minmax(0,1fr)]'>
        {/* Master: role list */}
        <div className='min-h-0 overflow-y-auto pr-1'>
          {roles.length === 0 ? (
            <p className='rounded-xl border border-dashed border-slate-200 py-10 text-center text-sm text-muted-foreground'>
              <Trans>No roles yet. Create one to get started.</Trans>
            </p>
          ) : (
            roles.map(role => (
              <RoleListItem
                key={role.id}
                role={role}
                memberCount={memberCounts.get(role.id) ?? 0}
                active={role.id === activeRoleId}
                selected={isSelected(role.id)}
                onOpen={() => setActiveRoleId(role.id)}
                onToggleSelect={() => {
                  select(role.id);
                }}
              />
            ))
          )}
        </div>

        {/* Detail: selected role */}
        <div className='min-h-0 rounded-xl border border-slate-200 bg-white p-5 shadow-sm'>
          <RoleDetailPanel role={activeRole} onEdit={openEdit} />
        </div>
      </div>

      <RoleFormDialog open={formOpen} role={editingRole} onClose={() => setFormOpen(false)} />
    </div>
  );
};
