// apps/frontend/src/modules/features/login/presentation/ui/Login.page.svelte
<script lang="ts">
  import LogoScylla from '@/assets/logo_scylla.png';
  import LogoScyllaDark from '@/assets/logo_scylla_dark.png';
  import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@shadcn';
  import { ScyllaLoadingScreen } from '@shared/presentation/ui';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import { LoginState } from '../login.state.svelte.ts';
  import LoginForm from './LoginForm.svelte';
  import { loginMessages } from './login.messages.ts';

  // Built here, in the component's initialisation: the mutation inside it
  // installs an effect, which needs an owner.
  const state = new LoginState();
</script>

{#if state.isSuccess}
  <ScyllaLoadingScreen />
{:else}
  <div class="flex flex-col items-center">
    <!--
      The wordmark is flat black and unreadable on the dark background, so the
      dark variant is the white cut of the same logo.

      Swapped by CSS rather than by reading the theme store: `index.html` puts
      `.dark` on <html> before the first paint, so this is right from the start,
      where a JS swap would paint the wrong logo first and flash.
    -->
    <img src={LogoScylla} alt="Scylla" class="h-2/6 w-2/6 dark:hidden" />
    <img src={LogoScyllaDark} alt="Scylla" class="hidden h-2/6 w-2/6 dark:block" />

    <Card class="w-full max-w-sm">
      <CardHeader>
        <CardTitle>{t(loginMessages.title)}</CardTitle>
        <CardDescription>{t(loginMessages.description)}</CardDescription>
      </CardHeader>
      <CardContent>
        <LoginForm handleSubmit={state.submit} isPending={state.isPending} />
      </CardContent>
    </Card>
  </div>
{/if}

// apps/frontend/src/modules/features/login/presentation/ui/Login.page.tsx
import { LoginForm } from '@/modules/features/login/presentation/ui/LoginForm.tsx';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/modules/shared/presentation/ui/shadcn';
import LogoScylla from '@/assets/logo_scylla.png';
import LogoScyllaDark from '@/assets/logo_scylla_dark.png';
import { Trans } from '@lingui/react/macro';
import { useLogin } from '@/modules/features/login/presentation/hooks/use-login.ts';
import { ScyllaLoadingScreen } from '@shared/presentation/ui';

/**
 * The wordmark is flat black, unreadable on the dark background — the dark
 * variant is the white cut of the same logo.
 *
 * Swapped by CSS rather than by reading the theme store: React only mounts
 * after the first paint, so a JS swap would paint the wrong logo first and
 * flash. The `.dark` class is on <html> before first paint, so this is right
 * from the start.
 */
const ScyllaLogo = ({ className }: { className: string }) => (
  <>
    <img src={LogoScylla} alt='Scylla' className={`${className} dark:hidden`} />
    <img src={LogoScyllaDark} alt='Scylla' className={`${className} hidden dark:block`} />
  </>
);

export const LoginPage = () => {
  const { mutate: login, isPending, isSuccess } = useLogin();

  const handleSubmit = (loginValue: string, passwordValue: string) => {
    login({ login: loginValue, password: passwordValue });
  };

  if (isSuccess) return <ScyllaLoadingScreen />;

  return (
    <div className={'flex items-center flex-col'}>
      <ScyllaLogo className='w-2/6 h-2/6' />
      <Card className='w-full max-w-sm'>
        <CardHeader>
          <CardTitle>
            <Trans>Login to your account</Trans>
          </CardTitle>
          <CardDescription>
            <Trans>Enter your username below to login to your account</Trans>
          </CardDescription>
        </CardHeader>
        <CardContent>
          <LoginForm handleSubmit={handleSubmit} isPending={isPending} />
        </CardContent>
      </Card>
    </div>
  );
};

export default LoginPage;
