// apps/frontend/src/modules/features/organization/presentation/ui/AddOrganizationDialog/AddOrganizationDialog.svelte
<script lang="ts">
  import { navigateTo } from '@platform/context';
  import { createMutation } from '@platform/query';
  import { FormDialog, type FormValues } from '@shared/presentation/ui';
  import {
    activeLocale,
    t,
  } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import { slugifyOrgName } from '@shared/utils/slug.ts';
  import { organizationMutations } from '../../organization.queries.ts';
  import { createOrganizationItems } from '../../utils/create-organization-form-items.ts';
  import { organizationMessages } from '../organization.messages.ts';

  interface Props {
    open: boolean;
    setOpen: (open: boolean) => void;
    hideCancel?: boolean;
  }

  let { open, setOpen, hideCancel = false }: Props = $props();

  const createOrganization = createMutation(() => organizationMutations.create());

  // The items resolve their labels with the Lingui macro at call time; reading
  // the active locale is what rebuilds them when it changes.
  const items = $derived((activeLocale(), createOrganizationItems()));

  const handleSubmit = ({ name, description }: FormValues<'name' | 'description'>) => {
    if (!name.trim()) return;

    createOrganization.mutate(
      { name, description: description.trim() || undefined },
      {
        // The mutation already makes the new organization the active one; this
        // is the part that only the caller knows — where to land afterwards.
        onSuccess: () => {
          setOpen(false);
          navigateTo(`/${slugifyOrgName(name)}/projects`);
        },
      },
    );
  };
</script>

<FormDialog
  {open}
  onOpenChange={setOpen}
  title={t(organizationMessages.createTitle)}
  description={t(organizationMessages.createDescription)}
  {items}
  isPending={createOrganization.isPending}
  submitLabel={t(organizationMessages.createSubmit)}
  onSubmit={handleSubmit}
  {hideCancel}
/>

// apps/frontend/src/modules/features/organization/presentation/ui/AddOrganizationDialog.tsx
import { useCreateOrganization } from '@/modules/features/organization/presentation/hooks/useCreateOrganization.ts';
import { Trans } from '@lingui/react/macro';
import { FormDialog } from '@shared/presentation/ui';
import { type FormChange } from '@shared/presentation/structs/scylla-form.struct.ts';
import { createOrganizationItems } from '@/modules/features/organization/presentation/utils/create-organization-form-items.ts';
import { useContextStore } from '@platform/context/use-context.store.ts';
import { useNavigate } from 'react-router-dom';
import { slugifyOrgName } from '@shared/utils/slug.ts';

interface AddOrganizationDialogProps {
  open: boolean;
  setOpen: (open: boolean) => void;
  hideCancel?: boolean;
}

export function AddOrganizationDialog({
  open,
  setOpen,
  hideCancel = false,
}: AddOrganizationDialogProps) {
  const createOrganization = useCreateOrganization();
  const setOrganization = useContextStore(state => state.setOrganization);
  const navigate = useNavigate();

  const handleSubmit = (values: FormChange[]) => {
    const name = values.find(v => v.id === 'name')?.value;
    const description = values.find(v => v.id === 'description')?.value;
    if (!name?.trim()) return;

    createOrganization.mutate(
      { name, description: description?.trim() || undefined },
      {
        onSuccess: data => {
          const orgId = data.id;
          setOpen(false);
          setOrganization(orgId, name);
          void navigate(`/${slugifyOrgName(name)}/projects`);
        },
      },
    );
  };

  return (
    <FormDialog
      open={open}
      onOpenChange={setOpen}
      title={<Trans>Create a new organization</Trans>}
      description={
        <Trans>
          Enter a name and description for your new organization. You can change these later in
          settings.
        </Trans>
      }
      items={createOrganizationItems()}
      isPending={createOrganization.isPending}
      submitLabel={<Trans>Create Organization</Trans>}
      onSubmit={handleSubmit}
      hideCancel={hideCancel}
    />
  );
}
