// apps/frontend/src/modules/features/role/presentation/ui/components/RoleDetailPanel.tsx
import { Trans } from '@lingui/react/macro';
import { ShieldCheck } from 'lucide-react';
import type { RoleEntity } from '@/modules/features/role/domain/entities/role.entity.ts';
import { RoleDetailHeader } from '@/modules/features/role/presentation/ui/components/role-detail/RoleDetailHeader.tsx';
import RoleDetailPermissions from '@/modules/features/role/presentation/ui/components/role-detail/RoleDetailPermissions.tsx';
import RoleDetailGrantList from '@/modules/features/role/presentation/ui/components/role-detail/RoleDetailGrantList.tsx';

interface RoleDetailPanelProps {
  role: RoleEntity | null;
  onEdit: (role: RoleEntity) => void;
}

export const RoleDetailPanel = ({ role, onEdit }: RoleDetailPanelProps) => {
  if (!role) {
    return (
      <div className='flex h-full flex-col items-center justify-center gap-3 text-center text-muted-foreground'>
        <div className='flex size-12 items-center justify-center rounded-xl bg-slate-100'>
          <ShieldCheck className='size-6 text-slate-400' />
        </div>
        <p className='text-sm'>
          <Trans>Select a role to see its permissions and members.</Trans>
        </p>
      </div>
    );
  }

  return (
    <div className='flex h-full flex-col gap-6 overflow-y-auto'>
      <RoleDetailHeader role={role} onEdit={onEdit} />
      <RoleDetailPermissions role={role} />
      <RoleDetailGrantList role={role} />
    </div>
  );
};

// apps/frontend/src/modules/features/roles/presentation/ui/components/RoleDetailPanel.svelte
<script lang="ts">
  import ShieldCheckIcon from '@lucide/svelte/icons/shield-check';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import type { RoleEntity } from '../../../domain/entities/role.entity.ts';
  import { rolesMessages } from '../roles.messages.ts';
  import RoleDetailGrantList from './role-detail/RoleDetailGrantList.svelte';
  import RoleDetailHeader from './role-detail/RoleDetailHeader.svelte';
  import RoleDetailPermissions from './role-detail/RoleDetailPermissions.svelte';

  interface Props {
    role: RoleEntity | null;
    onEdit: (role: RoleEntity) => void;
  }

  let { role, onEdit }: Props = $props();
</script>

{#if !role}
  <div
    class="flex h-full flex-col items-center justify-center gap-3 text-center text-muted-foreground"
  >
    <div class="flex size-12 items-center justify-center rounded-xl border">
      <ShieldCheckIcon class="size-6 text-slate-400" />
    </div>
    <p class="text-sm">{t(rolesMessages.selectARole)}</p>
  </div>
{:else}
  <!--
    Keyed on the role: the grant list and its target labels are ViewModels built
    at construction from the role they describe, so switching roles builds new
    ones rather than leaving the previous role's assignees on screen for a frame.
  -->
  {#key role.id}
    <div class="flex h-full flex-col gap-6 overflow-y-auto p-4">
      <RoleDetailHeader {role} {onEdit} />
      <RoleDetailPermissions {role} />
      <RoleDetailGrantList {role} />
    </div>
  {/key}
{/if}
