// apps/frontend/src/modules/features/roles/presentation/ui/components/role-form/RoleDialogPermissions.svelte
<script lang="ts">
  import { Badge, Checkbox, Label } from '@shadcn';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import type { Permission, PermissionScope } from '@platform/authz';
  import {
    getAlwaysGrantedPermissionsForScope,
    getEditablePermissionDefinitionsForScope,
    permissionLabelOf,
  } from '../../../utils/permission-mapping.ts';
  import { buildPermissionTree } from '../../../utils/permission-tree.ts';
  import { rolesMessages } from '../../roles.messages.ts';
  import CheckboxTree from './CheckboxTree.svelte';

  interface Props {
    scope: PermissionScope;
    permissions: Permission[];
    /**
     * How many permissions the role holds outside this build's catalog. They
     * are kept on save; the count is shown so nobody thinks they vanished.
     */
    preservedCount: number;
    /** What will actually be written — riders included. The honest count. */
    conferredCount: number;
    isPending: boolean;
    onPermissionsChange: (permissions: Permission[]) => void;
  }

  let {
    scope,
    permissions,
    preservedCount,
    conferredCount,
    isPending,
    onPermissionsChange,
  }: Props = $props();

  // Labels read against the *role's* scope, so a project permission conferred by
  // an organization role says "every project" rather than "the project".
  const labelForScope = (permission: Permission) => permissionLabelOf(permission, scope);

  const nodes = $derived(
    buildPermissionTree(getEditablePermissionDefinitionsForScope(scope), labelForScope),
  );

  /**
   * Conferred by construction at this scope, so shown ticked and locked rather
   * than hidden: the reader still learns the role carries it, and nobody can
   * build a role that admits someone to a place they cannot see.
   */
  const alwaysGranted = $derived(getAlwaysGrantedPermissionsForScope(scope));
</script>

<div class="flex flex-col gap-1.5">
  <div class="flex items-center justify-between">
    <Label>{t(rolesMessages.permissions)}</Label>
    <Badge variant="secondary">{t(rolesMessages.conferredCount(conferredCount))}</Badge>
  </div>

  <!-- Plain overflow rather than the shared `ScrollArea` — that root is only
       `relative`, so a fixed height on it clips nothing. -->
  <div class="h-56 overflow-y-auto rounded-lg border p-2">
    <div class="flex flex-col gap-0.5">
      {#each alwaysGranted as permission (permission)}
        <label
          class="flex cursor-not-allowed items-center gap-2 rounded-md px-2 py-1.5"
          aria-disabled="true"
        >
          <Checkbox checked disabled aria-label={labelForScope(permission)} />
          <span class="text-sm">{labelForScope(permission)}</span>
          <Badge variant="outline" class="ml-auto text-[10px]">{t(rolesMessages.always)}</Badge>
        </label>
      {/each}

      <!--
        Keyed on the scope: switching it rebuilds the tree from another catalog
        slice, and the component seeds its checked set once, at construction.
      -->
      {#key scope}
        <CheckboxTree
          {nodes}
          checkedIds={permissions}
          allDisabled={isPending}
          onCheckedChange={onPermissionsChange}
        />
      {/key}
    </div>
  </div>

  {#if alwaysGranted.length > 0}
    <p class="text-xs text-muted-foreground">{t(rolesMessages.alwaysGrantedNote)}</p>
  {/if}
  {#if preservedCount > 0}
    <p class="text-xs text-muted-foreground">{t(rolesMessages.preservedNote(preservedCount))}</p>
  {/if}
</div>

// apps/frontend/src/modules/features/permission/presentation/ui/components/role-form/RoleDialogPermissions.tsx
import { useCallback, useMemo } from 'react';
import { Badge, Label } from '@shadcn';
import { Trans } from '@lingui/react/macro';
import { Checkbox } from '@shadcn/checkbox.tsx';
import { ScrollArea } from '@shadcn/scroll-area.tsx';
import { CheckboxTree } from '@shared/presentation/ui/forms/CheckboxTree.tsx';
import type {
  Permission,
  PermissionScope,
} from '@/modules/features/permission/domain/structs/permission.struct.ts';
import {
  getAlwaysGrantedPermissionsForScope,
  getEditablePermissionDefinitionsForScope,
  withImplicitPermissions,
} from '@/modules/features/permission/presentation/utils/permission-mapping.ts';
import { buildPermissionTree } from '@/modules/features/permission/presentation/utils/permission-tree.ts';
import { usePermissionLabels } from '@/modules/features/permission/presentation/hooks/use-permission-labels.ts';

interface RoleDialogPermissionsProps {
  scope: PermissionScope;
  permissions: Permission[];
  /**
   * How many permissions the role holds outside this build's catalog. They are
   * kept on save; the count is shown so nobody thinks they vanished.
   */
  preservedCount: number;
  isPending: boolean;
  onPermissionsChange: (permissions: Permission[]) => void;
}

export const RoleDialogPermissions = ({
  scope,
  permissions,
  preservedCount,
  isPending,
  onPermissionsChange,
}: RoleDialogPermissionsProps) => {
  const { permissionLabel } = usePermissionLabels();

  // Labels read against the *role's* scope, so a project permission conferred by
  // an organization role says "every project" rather than "the project".
  const labelForScope = useCallback(
    (permission: Permission) => permissionLabel(permission, scope),
    [permissionLabel, scope],
  );

  const permissionNodes = useMemo(
    () => buildPermissionTree(getEditablePermissionDefinitionsForScope(scope), labelForScope),
    [scope, labelForScope],
  );

  /**
   * Conferred by construction at this scope, so shown ticked and locked rather
   * than hidden: the reader still learns the role carries it, and nobody can
   * build a role that admits someone to a place they cannot see.
   */
  const alwaysGranted = useMemo(() => getAlwaysGrantedPermissionsForScope(scope), [scope]);

  /** What will actually be written — riders included. The honest count. */
  const conferredCount = useMemo(
    () => withImplicitPermissions(scope, permissions).length,
    [scope, permissions],
  );

  return (
    <div className='flex flex-col gap-1.5'>
      <div className='flex items-center justify-between'>
        <Label>
          <Trans>Permissions</Trans>
        </Label>
        <Badge variant='secondary'>
          <Trans>{conferredCount} selected</Trans>
        </Badge>
      </div>
      <ScrollArea className='h-56 rounded-lg border border-slate-200 p-2'>
        <div className='flex flex-col gap-0.5'>
          {alwaysGranted.map(permission => (
            <label
              key={permission}
              className='flex items-center gap-2 rounded-md px-2 py-1.5 cursor-not-allowed'
              aria-disabled
            >
              <Checkbox checked disabled />
              <span className='text-sm'>{labelForScope(permission)}</span>
              <Badge variant='outline' className='ml-auto text-[10px]'>
                <Trans>Always</Trans>
              </Badge>
            </label>
          ))}
          <CheckboxTree
            allDisabled={isPending}
            nodes={permissionNodes}
            defaultCheckedIds={permissions}
            onCheckedChange={onPermissionsChange}
          />
        </div>
      </ScrollArea>
      {alwaysGranted.length > 0 && (
        <p className='text-xs text-muted-foreground'>
          <Trans>
            Holding a role in an organization is what belonging to it means, so every organization
            role carries it. An organization role applies to every project of the organization.
          </Trans>
        </p>
      )}
      {preservedCount > 0 && (
        <p className='text-xs text-muted-foreground'>
          <Trans>
            This role also holds {preservedCount} permission(s) not managed here. They are kept
            unchanged.
          </Trans>
        </p>
      )}
    </div>
  );
};
