// apps/frontend/src/modules/features/secret/presentation/ui/components/SecretHeader.tsx
import { Trans } from '@lingui/react/macro';
import { FeatureHeader } from '@shared/presentation/ui';
import { useFeatureSelection } from '@shared/presentation/hooks/use-feature-selection.ts';
import { useDeleteSecret } from '@/modules/features/secret/presentation/hooks/use-secrets.ts';
import { Permission } from '@platform/authz/domain/structs/permission.struct.ts';
import { useCan } from '@platform/authz/presentation/hooks/use-authorization.ts';

interface CredentialsHeaderProps {
  activeCount: number;
  secretIds: string[];
  onAddSecret?: () => void;
  projectId: string;
}

export const SecretHeader = ({
  activeCount,
  secretIds,
  onAddSecret,
  projectId,
}: CredentialsHeaderProps) => {
  const deleteSecret = useDeleteSecret(projectId);
  const { headerProps } = useFeatureSelection('secrets', secretIds, {
    deleteItem: id => deleteSecret.mutateAsync(id),
  });

  const canCreate = useCan(Permission.CREATE_SECRET, { projectId });
  const canDelete = useCan(Permission.DELETE_SECRET, { projectId });

  return (
    <FeatureHeader
      count={activeCount}
      label={<Trans>Secret</Trans>}
      pluralLabel={<Trans>Secrets</Trans>}
      onNew={onAddSecret}
      newLabel={<Trans>New secret</Trans>}
      canNew={canCreate}
      newDeniedReason={<Trans>You don't have permission to create secrets.</Trans>}
      canDelete={canDelete}
      deleteDeniedReason={<Trans>You don't have permission to delete secrets.</Trans>}
      {...headerProps}
    />
  );
};

// apps/frontend/src/modules/features/secret/presentation/ui/components/SecretHeader.svelte
<script lang="ts">
  import { can, Permission } from '@platform/authz';
  import { createMutation } from '@platform/query';
  import { FeatureHeader } from '@shared/presentation/ui-svelte';
  import { createFeatureSelection } from '@shared/presentation/state/feature-selection.svelte.ts';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import { secretMutations } from '../../secret.queries.ts';
  import { secretMessages } from '../secret.messages.ts';

  interface Props {
    activeCount: number;
    secretIds: string[];
    projectId: string;
    onAddSecret?: () => void;
  }

  let { activeCount, secretIds, projectId, onAddSecret }: Props = $props();

  const deleteSecret = createMutation(() => secretMutations.remove(projectId));

  // A getter, not the array: the ids are server data that arrives late, and
  // capturing them once would freeze "select all" on the first, empty render.
  const selection = createFeatureSelection('secrets', () => secretIds, {
    deleteItem: id => deleteSecret.mutateAsync(id),
  });

  const canCreate = $derived(can(Permission.CREATE_SECRET, { projectId }));
  const canDelete = $derived(can(Permission.DELETE_SECRET, { projectId }));
</script>

<FeatureHeader
  count={activeCount}
  label={t(secretMessages.secret)}
  pluralLabel={t(secretMessages.secrets)}
  onNew={onAddSecret}
  newLabel={t(secretMessages.newSecret)}
  canNew={canCreate}
  newDeniedReason={t(secretMessages.createDenied)}
  {canDelete}
  deleteDeniedReason={t(secretMessages.deleteDenied)}
  {...selection.headerProps}
/>
